# -- --
FROM python:3.9-slim

# -- install required packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    neovim \
    curl \
    git \
    ca-certificates \
    less \
    && pip install mkdocs mkdocs-material mkdocs-awesome-pages-plugin mkdocs-github-admonitions-plugin \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Build args for user info
ARG UID=1000
ARG GID=1000
ARG USERNAME=docsuser

# -- create group, user, and set permissions
RUN addgroup --gid ${GID} ${USERNAME} && \
    adduser --disabled-password --uid ${UID} --gid ${GID} ${USERNAME}

COPY docs /docs/docs
COPY mkdocs.yaml /docs/mkdocs.yaml
# -- set working dir
WORKDIR /docs

# -- run as user
USER ${USERNAME}

EXPOSE 8000
CMD ["mkdocs", "serve", "-a", "0.0.0.0:8000"]
